### ISSUE TITLE
About TeaSpeak

### ISSUE THREAD

**Issue by b00tkitism** [WolverinDEV/bclean#1]
Hi, I hope you are doing well.
I'm Mahdi, a high-school student and reverse engineering, C/C++ lover.
I was trying to reverse engineer teamspeak for the last 2 weeks, and randomly, I saw your project TeaSpeak. As I saw, its development is stopped now, and I thought if you could make it open-source or give source code access to me so I can continue its development.
Thanks.
I'm also available on Telegram if you are more comfortable talking there: t.me/b00tkitism

**Comment by WolverinDEV** [comment]
https://git.did.science/TeaSpeak :)
PS: I'm more into Discord then Telegram :D

**Comment by b00tkitism** [comment]
@WolverinDEV, thanks for your answer, I'll start contributing to TeaSpeak.
Can I have your discord?

**Comment by WolverinDEV** [comment]
I'll have to add you on Discord as you can not add me :)

**Comment by b00tkitism** [comment]
So can you add me? id: akam4hdi

**Comment by b00tkitism** [comment]
@WolverinDEV sorry, does it contain all codes? I can't build the server using cmake. I checked the gitlab again, and I saw a repository of the server project is hidden

**Comment by WolverinDEV** [comment]
Well, that's odd.  
Do you know which repository exactly?

**Comment by b00tkitism** [comment]
![Screenshot_20240615_201223_Samsung Internet.jpg](https://github.com/WolverinDEV/bclean/assets/119131616/d1723e06-b66b-4538-9a34-669ad87be19e)
As you can see in the top right, it says the repository count of Server project is 4, but only 3 of them is visible

**Comment by WolverinDEV** [comment]
No, only three of the four repositories are hosted on gitlab. One is hosted on GitHub :)

**Comment by b00tkitism** [comment]
@WolverinDEV can you check your discord please?

**Comment by b00tkitism** [comment]
@WolverinDEV can you check your discord please?

**Comment by b00tkitism** [comment]
@WolverinDEV https://git.did.science/TeaSpeak/Server/teafile This repo is private. Can you make it public? I need to build TeaSpeak from the source code, and it's failed because this repo is private.
I know you don't like me asking things about TeaSpeak, but for building the server, I need this repo please don't ignore me this time
